<?php echo $this->doctype(); ?>

<html lang="pt-br">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('MercadoLivre'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <?php
        // CSS
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => 'http://static.mlstatic.com/org-img/chico/img/favicon.ico?new'))
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
                        ->prependStylesheet($this->basePath() . '/js/jquery-ui-1.10.4.custom/css/ui-lightness/jquery-ui-1.10.4.custom.min.css'); ?>

        <?php 
        // JS
        $this->inlineScript()
                        ->prependFile($this->basePath() . '/Application/js/Application.js')
                        ->prependFile($this->basePath() . '/js/angular.min.js')
                        ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                        ->prependFile($this->basePath() . '/js/jquery-ui-1.10.4.custom/js/jquery-ui-1.10.4.custom.min.js')
                        ->prependFile($this->basePath() . '/js/jquery.min.js')
                        ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                        ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>
    </head>
    <body ng-app="application">
        <?php echo $this->content; ?>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
