<div class="container user-footer">
    <div class="row user-footer-about">
        <div class="col-md-12">
            Copyright © 1999-2014 Ebazar.com.br LTDA.
            <a href="http://contato.mercadolivre.com.br/seguro_terminos" target="_blank">Termos e condições | </a>
            <a href="http://contato.mercadolivre.com.br/seguro_privacidad" target="_blank">Política de privacidade | </a>
            <a href="http://contato.mercadolivre.com.br/" target="_blank">Contato</a><br>
            CNPJ n.º 03.007.331/0001-41 / Avenida Marte, 489, Térreo, Parte A / Santana de Parnaíba-SP / CEP: 06541-005 - empresa do grupo MercadoLivre. 
        </div>
    </div>
</div>