<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container-fluid user-header">
        <div class="row-fluid">
            <div class="container">
                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-7 col-lg-7">
                        <center>
                            <div class="user-logo">
                                <a href="/universidade/index">
                                    <img src="#" alt="MercadoLivre" />
                                </a>
                            </div>
                        </center>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-5 col-lg-5">
                        <div class="user-social">
                            <a href="http://www.facebook.com.br/mercadolivre" class="user-social-fb"></a>
                            <a href="http://www.twitter.com.br/mercadolivre" class="user-social-tt"></a>
                        </div>
                        <div class="user-menu">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</nav>