<div class="row">
    <div class="col-md-2">
        <ul class="nav nav-pills nav-stacked">
            <li role="presentation" class="active"><a href="#">Usuarios</a></li>
            <li role="presentation"><a href="#">Grupos</a></li>
        </ul>
    </div>

    <div class="col-md-7">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Formulario') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo $this->translate('Donec congue blandit luctus. Praesent varius sem interdum tortor ultrices, id euismod magna lobortis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.') ?></p>
                <p><?php echo $this->translate('Donec congue blandit luctus. Praesent varius sem interdum tortor ultrices, id euismod magna lobortis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.') ?></p>
                <p><?php echo $this->translate('Donec congue blandit luctus. Praesent varius sem interdum tortor ultrices, id euismod magna lobortis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.') ?></p>
                <p><?php echo $this->translate('Donec congue blandit luctus. Praesent varius sem interdum tortor ultrices, id euismod magna lobortis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.') ?></p>
                <p><?php echo $this->translate('Donec congue blandit luctus. Praesent varius sem interdum tortor ultrices, id euismod magna lobortis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.') ?></p>
                <p><?php echo $this->translate('Donec congue blandit luctus. Praesent varius sem interdum tortor ultrices, id euismod magna lobortis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.') ?></p>
                <p><?php echo $this->translate('Donec congue blandit luctus. Praesent varius sem interdum tortor ultrices, id euismod magna lobortis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.') ?></p>
                <p><?php echo $this->translate('Donec congue blandit luctus. Praesent varius sem interdum tortor ultrices, id euismod magna lobortis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.') ?></p>
            </div>
        </div>
    </div>

    <div class="col-md-3">
        <div class="list-group">
            <a href="#" class="list-group-item active">admin</a>
            <a href="#" class="list-group-item">muriloacs</a>
            <a href="#" class="list-group-item">breno69</a>
            <a href="#" class="list-group-item">vaitimao</a>
        </div>
    </div>
</div>