<div class="jumbotron">
    <h1><?php echo sprintf($this->translate('Lorem ipsum dolor sit amet.'), '<span class="zf-green">', '</span>') ?></h1>
    <p><?php echo $this->translate('Sed ac nisl eget mauris aliquam tincidunt at sit amet mauris. Aliquam faucibus nisi vitae mollis aliquam. Nulla viverra gravida sapien vel sollicitudin. Aliquam condimentum eros vel est laoreet, ultrices interdum ex volutpat. Ut est dui, pellentesque pellentesque imperdiet ultricies, vehicula et magna.') ?></p>
</div>

<div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Sistema') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo $this->translate('Donec congue blandit luctus. Praesent varius sem interdum tortor ultrices, id euismod magna lobortis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.') ?></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Versão') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo $this->translate('Donec congue blandit luctus. Praesent varius sem interdum tortor ultrices, id euismod magna lobortis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.') ?></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Suporte') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo $this->translate('Donec congue blandit luctus. Praesent varius sem interdum tortor ultrices, id euismod magna lobortis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.') ?></p>
            </div>
        </div>
    </div>
</div>